### ISSUE TITLE
iOS 12 and 13 crash upon launch

### ISSUE THREAD

**Issue by shadowscott** [UInt2048/CyberKit#2]
<details>
<summary>Original issue report information</summary>

V0.0.6 alpha

Crash log: https://pastebin.com/2nd9weWT

System log errors:

- Could not load the "gear" image referenced from a nib in the bundle with identifier "org.webkit.MobileMiniBrowserFramework"

- CGBitmapContextCreateImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

</details>

**Comment by UInt2048** [comment]
This issue also applies to v0.0.5 alpha although you will receive a different error.

**Comment by shadowscott** [comment]
> This issue also applies to v0.0.5 alpha although you will receive a different error.

Yep I got these errors on both alpha 0.0.5q and 0.0.6 but as you said on reddit it was the same build. Saw that you wanted to move things to github so I posted here.

**Comment by UInt2048** [comment]
Just to clarify the current status, this project does not officially support iOS 13 yet. 0.0.6 nightly builds have demonstrated that iOS 12 and 13 support will be jointly released, as they now are both at the exact same stage. This seems to hinge on replacing RunningBoardServices.framework with AssertionServices.framework correctly. Unfortunately, while I am working on it, there may be times where I have other obligations.

Consequently, there is no ETA on the release.

**Comment by UInt2048** [comment]
The release of 0.0.7 alpha is because of #5. iOS 12 and 13 are still unfortunately not supported yet.

**Comment by UInt2048** [comment]
If you expected "officially working" by the time you read this message, I unfortunately cannot say that is the case. However, for a while now, this issue has been more broadly interpreted than its original meaning of a crash on iOS 13 within a few seconds of launch.

I presume you will observe at minimum that tonight's 0.0.7 nightly release demonstrates this no longer occurs, which means this issue is now closed.

@shadowscott Please feel free to test different sites and report new issues based on the conditions you observe.
